### ISSUE TITLE
Crashed when running distributed CPU training using 2 nodes

### ISSUE THREAD

**Issue by kaixuanliu** [alibaba/graphlearn-for-pytorch#30]
### 🐛 Describe the bug

Hi @husimplicity @baoleai , I updated the latest code, and can build pure CPU version GLTorch. And I have managed to run CPU-version distributed training on one single node. However, when I run distributed training on different nodes, it returned error like this:
`Traceback (most recent call last):
  File "/panfs/users/liukaixu/env/gltorch-cpu/lib/python3.8/site-packages/graphlearn_torch/distributed/dist_loader.py", line 227, in '__del__'
    self.shutdown()
  File "/panfs/users/liukaixu/env/gltorch-cpu/lib/python3.8/site-packages/graphlearn_torch/distributed/dist_loader.py", line 230, in shutdown
    if self._shutdowned:
AttributeError: 'DistNeighborLoader' object has no attribute '_shutdowned'
Exception ignored in: <function DistLoader.__del__ at 0x148225431550>
Traceback (most recent call last):
  File "/panfs/users/liukaixu/env/gltorch-cpu/lib/python3.8/site-packages/graphlearn_torch/distributed/dist_loader.py", line 227, in '__del__'
    self.shutdown()
  File "/panfs/users/liukaixu/env/gltorch-cpu/lib/python3.8/site-packages/graphlearn_torch/distributed/dist_loader.py", line 230, in shutdown
    if self._shutdowned:
AttributeError: 'DistNeighborLoader' object has no attribute '_shutdowned'
Traceback (most recent call last):
  File "dist_train_rgnn.py", line 300, in <module>
    torch.multiprocessing.spawn(
  File "/panfs/users/liukaixu/env/gltorch-cpu/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/panfs/users/liukaixu/env/gltorch-cpu/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/panfs/users/liukaixu/env/gltorch-cpu/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/panfs/users/liukaixu/env/gltorch-cpu/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/global/panfs01/users/liukaixu/graphlearn-for-pytorch/examples/igbh/dist_train_rgnn.py", line 84, in run_training_proc
    train_loader = glt.distributed.DistNeighborLoader(
  File "/panfs/users/liukaixu/env/gltorch-cpu/lib/python3.8/site-packages/graphlearn_torch/distributed/dist_neighbor_loader.py", line 92, in __init__
    super().__init__(
  File "/panfs/users/liukaixu/env/gltorch-cpu/lib/python3.8/site-packages/graphlearn_torch/distributed/dist_loader.py", line 177, in __init__
    self._channel = ShmChannel(self.worker_options.channel_capacity,
  File "/panfs/users/liukaixu/env/gltorch-cpu/lib/python3.8/site-packages/graphlearn_torch/channel/shm_channel.py", line 48, in __init__
    self._queue = pywrap.SampleQueue(capacity, shm_size)
AttributeError: module 'graphlearn_torch.py_graphlearn_torch' has no attribute 'SampleQueue'`

cmd lines are: 
`#node 0:
python dist_train_rgnn.py --num_nodes=2 --node_rank=0 --num_training_procs=2 --master_addr=eedq004 --model='rgat' --dataset_size='tiny' --num_classes=19 --cpu_mode

#node 1:
python dist_train_rgnn.py --num_nodes=2 --node_rank=1 --num_training_procs=2 --master_addr=eedq004 --model='rgat' --dataset_size='tiny' --num_classes=19 --cpu_mode`

where eedq004 is the hostname of node 0.

### Environment

* GLT version: 0.2.0 (build from latest source code)
* PyG version:  2.3.1
* PyTorch version: 1.13.1+cpu
* OS: Rocky Linux release 8.7 (Green Obsidian)
* Python version: 3.8.16
* CUDA/cuDNN version: No
* Any other relevant information

**Comment by husimplicity** [comment]
Have you reinstall by `pip install --force-reinstall dist/*`?

**Comment by baoleai** [comment]
likely duplicate of #26

**Comment by kaixuanliu** [comment]
Sorry, there is code mismatch between 2 nodes. It works now. We can close this issue.
